services:
  db:
    image: postgres:17-alpine
    container_name: swapp-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Valentin_03
      POSTGRES_DB: swapp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./swapp-backend
    container_name: swapp-backend
    ports:
      - "7860:7860"
    volumes:
      - ./swapp-backend/uploads:/app/uploads
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:Valentin_03@db:5432/swapp_db
    restart: always

  frontend:
    build: ./swapp-frontend
    container_name: swapp-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:7860"
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
