services:
  backend:
    build: ./swapp-backend
    ports:
      - "7860:7860"
    env_file:
      - ./swapp-backend/.env
    # Un solo bloque volumes para el backend
    volumes:
      - ./swapp-backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 7860 --reload

  frontend:
    build: ./swapp-frontend
    ports:
      - "3000:3000"
    # Un solo bloque volumes para el frontend
    volumes:
      - ./swapp-frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
