services:
  db:
    image: postgres:15-alpine
    container_name: swapp-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: swapp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./swapp-backend
    container_name: swapp-backend
    ports:
      - "7860:7860"
    volumes:
      - ./swapp-backend/uploads:/app/uploads
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASS}@db:5432/swapp_db
      SECRET_KEY: ${SECRET_KEY}
    restart: always

  frontend:
    build:
      context: ./swapp-frontend
      args:
        NEXT_PUBLIC_API_URL: ${API_URL}
    container_name: swapp-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: ${API_URL}
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
