import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import Header from "@/components/swapp/Header";
import BottomNav from "@/components/swapp/BottomNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Swapp Demo",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="es">
			<body
				className={`${inter.className} bg-gray-200 min-h-screen flex justify-center`}>
				<AuthProvider>
					<div className="w-full max-w-md bg-white min-h-screen shadow-2xl relative flex flex-col overflow-hidden">
						<Header />

						<main className="flex-1 overflow-y-auto bg-[linear-gradient(to_bottom,#172638_0%,#132D46_10%,#0A786A_20%,#01C38E_35%,#80E1C7_45%,#FFFFFF_60%,#f0f1f4_70%)] pb-24">
							{children}
						</main>

						{/* --- NUEVA BOTTOM NAVIGATION INTELIGENTE --- */}
						<BottomNav />
					</div>
				</AuthProvider>
			</body>
		</html>
	);
}
