import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import Header from "@/components/swapp/Header";
import BottomNav from "@/components/swapp/BottomNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Swapp Demo",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="es">
			<body
				className={`${inter.className} bg-gray-200 h-[100dvh] flex justify-center overflow-hidden`}>
				<AuthProvider>
					<div className="w-full max-w-md bg-white h-full shadow-2xl relative flex flex-col overflow-hidden">
						<Header />

						<main className="flex-1 overflow-hidden bg-swapp-gradient pb-24 relative">
							{children}
						</main>

						<BottomNav />
					</div>
				</AuthProvider>
			</body>
		</html>
	);
}
