"""test_refactor_models

Revision ID: 4653a8cbeab6
Revises: 8d7af7a99bfe
Create Date: 2026-08-18 12:49:52.733121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4653a8cbeab6'
down_revision: Union[str, None] = '8d7af7a99bfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory_movements', 'movement_uuid',
               existing_type=sa.UUID(),
               nullable=True,
               existing_server_default=sa.text('gen_random_uuid()'),
               schema='swapp')
    op.alter_column('inventory_movements', 'unit_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Costo por unidad pagado en este lote (obligatorio para purchases)',
               existing_nullable=True,
               schema='swapp')
    op.drop_index('idx_inventory_movements_created', table_name='inventory_movements', schema='swapp')
    op.drop_index('idx_inventory_movements_product', table_name='inventory_movements', schema='swapp')
    op.drop_index('idx_inventory_movements_reference', table_name='inventory_movements', schema='swapp')
    op.drop_index('idx_inventory_movements_type', table_name='inventory_movements', schema='swapp')
    op.create_index(op.f('ix_swapp_inventory_movements_movement_id'), 'inventory_movements', ['movement_id'], unique=False, schema='swapp')
    op.alter_column('product_categories', 'parent_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Categoría padre (NULL si es nivel 1)',
               existing_nullable=True,
               schema='swapp')
    op.alter_column('product_categories', 'level',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Nivel: 1=raíz, 2=hijo, 3=nieto, etc.',
               existing_nullable=True,
               schema='swapp')
    op.drop_index('idx_categories_level', table_name='product_categories', schema='swapp')
    op.drop_index('idx_categories_parent', table_name='product_categories', schema='swapp')
    op.drop_index('idx_categories_path_ids', table_name='product_categories', schema='swapp', postgresql_using='gin')
    op.drop_index('idx_categories_slug', table_name='product_categories', schema='swapp')
    op.drop_table_comment(
        'product_categories',
        existing_comment='Categorías jerárquicas de productos',
        schema='swapp'
    )
    op.drop_index('idx_discounts_dates', table_name='product_discounts', schema='swapp')
    op.drop_index('idx_discounts_product', table_name='product_discounts', schema='swapp')
    op.drop_table_comment(
        'product_discounts',
        existing_comment='Motor de ofertas temporales por producto',
        schema='swapp'
    )
    op.drop_index('idx_product_media_order', table_name='product_media', schema='swapp')
    op.drop_index('idx_product_media_product', table_name='product_media', schema='swapp')
    op.drop_index('idx_product_media_type', table_name='product_media', schema='swapp')
    op.alter_column('product_price_history', 'record_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Indica si el cambio fue en el precio de venta (base_price) o costo de reposición (cost_price)',
               existing_nullable=False,
               existing_server_default=sa.text("'base_price'::character varying"),
               schema='swapp')
    op.drop_table_comment(
        'product_price_history',
        existing_comment='Registro inmutable de los cambios de precio de los productos',
        schema='swapp'
    )
    op.drop_index('idx_product_rel_confidence', table_name='product_relationships', schema='swapp')
    op.drop_index('idx_product_rel_priority', table_name='product_relationships', schema='swapp')
    op.drop_index('idx_product_rel_source', table_name='product_relationships', schema='swapp')
    op.drop_index('idx_product_rel_source_type', table_name='product_relationships', schema='swapp')
    op.drop_index('idx_product_rel_target', table_name='product_relationships', schema='swapp')
    op.drop_index('idx_product_rel_target_type', table_name='product_relationships', schema='swapp')
    op.drop_index('idx_product_rel_type', table_name='product_relationships', schema='swapp')
    op.drop_constraint('unique_relationship', 'product_relationships', schema='swapp', type_='unique')
    op.drop_constraint('product_relationships_updated_by_fkey', 'product_relationships', schema='swapp', type_='foreignkey')
    op.drop_constraint('product_relationships_created_by_fkey', 'product_relationships', schema='swapp', type_='foreignkey')
    op.create_foreign_key(None, 'product_relationships', 'staff_users', ['created_by'], ['staff_id'], source_schema='swapp', referent_schema='swapp')
    op.create_foreign_key(None, 'product_relationships', 'staff_users', ['updated_by'], ['staff_id'], source_schema='swapp', referent_schema='swapp')
    op.alter_column('products', 'sku',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Código único del producto para inventario',
               existing_nullable=True,
               schema='swapp')
    op.alter_column('products', 'slug',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='URL amigable: nombre-del-producto',
               existing_nullable=False,
               schema='swapp')
    op.alter_column('products', 'base_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Precio regular sin descuento',
               existing_nullable=False,
               schema='swapp')
    op.alter_column('products', 'cost_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               schema='swapp')
    op.alter_column('products', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Indica si el producto está activo en el sistema (permite ocultar sin eliminar)',
               existing_nullable=False,
               existing_server_default=sa.text('true'),
               schema='swapp')
    op.alter_column('products', 'is_returnable',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Indica si el producto puede ser devuelto por el cliente',
               existing_nullable=False,
               existing_server_default=sa.text('false'),
               schema='swapp')
    op.alter_column('products', 'tax_class_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True,
               schema='swapp')
    op.drop_index('idx_products_category', table_name='products', schema='swapp')
    op.drop_index('idx_products_created_at', table_name='products', schema='swapp')
    op.drop_index('idx_products_deleted', table_name='products', schema='swapp', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_products_featured', table_name='products', schema='swapp')
    op.drop_index('idx_products_published', table_name='products', schema='swapp')
    op.drop_index('idx_products_sku', table_name='products', schema='swapp')
    op.drop_index('idx_products_slug', table_name='products', schema='swapp')
    op.drop_index('idx_products_type', table_name='products', schema='swapp')
    op.drop_constraint('products_sku_key', 'products', schema='swapp', type_='unique')
    op.create_index(op.f('ix_swapp_products_sku'), 'products', ['sku'], unique=True, schema='swapp')
    op.drop_table_comment(
        'products',
        existing_comment='Catálogo de productos de la aplicación',
        schema='swapp'
    )
    op.alter_column('staff_users', 'last_login_user_agent',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               schema='swapp')
    op.drop_index('idx_staff_users_active', table_name='staff_users', schema='swapp')
    op.drop_index('idx_staff_users_deleted', table_name='staff_users', schema='swapp', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_staff_users_email', table_name='staff_users', schema='swapp')
    op.drop_index('idx_staff_users_role', table_name='staff_users', schema='swapp')
    op.drop_constraint('staff_users_email_key', 'staff_users', schema='swapp', type_='unique')
    op.create_index(op.f('ix_swapp_staff_users_email'), 'staff_users', ['email'], unique=True, schema='swapp')
    op.create_index(op.f('ix_swapp_staff_users_staff_id'), 'staff_users', ['staff_id'], unique=False, schema='swapp')
    op.alter_column('tax_classes', 'tax_class_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('swapp.tax_classes_tax_class_id_seq'::regclass)"),
               schema='swapp')
    op.alter_column('user_image_analyses', 'recognition_status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Estado del reconocimiento: pending, processing, completed, failed, no_match',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"),
               schema='swapp')
    op.alter_column('user_image_analyses', 'confidence_score',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               comment=None,
               existing_comment='Precisión del reconocimiento (0-1)',
               existing_nullable=True,
               schema='swapp')
    op.alter_column('user_image_analyses', 'modelarts_response',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Respuesta completa de ModelArts para debugging y reentrenamiento',
               existing_nullable=True,
               schema='swapp')
    op.alter_column('user_image_analyses', 'detection_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Detalles de objetos detectados con bounding boxes',
               existing_nullable=True,
               schema='swapp')
    op.alter_column('user_image_analyses', 'user_feedback',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Feedback del usuario: correct, incorrect, not_sure',
               existing_nullable=True,
               schema='swapp')
    op.drop_index('idx_user_image_confidence', table_name='user_image_analyses', schema='swapp')
    op.drop_index('idx_user_image_detection', table_name='user_image_analyses', schema='swapp', postgresql_using='gin')
    op.drop_index('idx_user_image_labels', table_name='user_image_analyses', schema='swapp', postgresql_using='gin')
    op.drop_index('idx_user_image_modelarts', table_name='user_image_analyses', schema='swapp', postgresql_using='gin')
    op.drop_index('idx_user_image_product', table_name='user_image_analyses', schema='swapp')
    op.drop_index('idx_user_image_recognized_product', table_name='user_image_analyses', schema='swapp')
    op.drop_index('idx_user_image_status', table_name='user_image_analyses', schema='swapp')
    op.drop_index('idx_user_image_upload', table_name='user_image_analyses', schema='swapp')
    op.drop_index('idx_user_image_user', table_name='user_image_analyses', schema='swapp')
    op.drop_table_comment(
        'user_image_analyses',
        existing_comment='Registro de imágenes subidas por usuarios y su análisis por IA',
        schema='swapp'
    )
    op.alter_column('users', 'user_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Identificador numérico autoincremental',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('swapp.users_user_id_seq'::regclass)"),
               schema='swapp')
    op.alter_column('users', 'user_uuid',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Identificador UUID público para APIs',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'),
               schema='swapp')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Email único del usuario',
               existing_nullable=False,
               schema='swapp')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Hash de la contraseña (bcrypt/argon2)',
               existing_nullable=False,
               schema='swapp')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Rol del usuario: user, admin, moderator, etc.',
               existing_nullable=False,
               existing_server_default=sa.text("'user'::character varying"),
               schema='swapp')
    op.alter_column('users', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Soft delete: NULL = activo, fecha = eliminado',
               existing_nullable=True,
               schema='swapp')
    op.drop_index('idx_users_created_at', table_name='users', schema='swapp')
    op.drop_index('idx_users_deleted_at', table_name='users', schema='swapp', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_users_email', table_name='users', schema='swapp')
    op.drop_index('idx_users_metadata', table_name='users', schema='swapp', postgresql_using='gin')
    op.drop_index('idx_users_role', table_name='users', schema='swapp')
    op.drop_index('idx_users_settings', table_name='users', schema='swapp', postgresql_using='gin')
    op.drop_index('idx_users_user_uuid', table_name='users', schema='swapp')
    op.drop_index('idx_users_username', table_name='users', schema='swapp')
    op.drop_constraint('users_email_key', 'users', schema='swapp', type_='unique')
    op.create_index(op.f('ix_swapp_users_email'), 'users', ['email'], unique=True, schema='swapp')
    op.drop_constraint('users_created_by_fkey', 'users', schema='swapp', type_='foreignkey')
    op.drop_constraint('users_updated_by_fkey', 'users', schema='swapp', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'staff_users', ['created_by'], ['staff_id'], source_schema='swapp', referent_schema='swapp')
    op.create_foreign_key(None, 'users', 'staff_users', ['updated_by'], ['staff_id'], source_schema='swapp', referent_schema='swapp')
    op.drop_table_comment(
        'users',
        existing_comment='Almacena información de usuarios de la aplicación',
        schema='swapp'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'users',
        'Almacena información de usuarios de la aplicación',
        existing_comment=None,
        schema='swapp'
    )
    op.drop_constraint(None, 'users', schema='swapp', type_='foreignkey')
    op.drop_constraint(None, 'users', schema='swapp', type_='foreignkey')
    op.create_foreign_key('users_updated_by_fkey', 'users', 'users', ['updated_by'], ['user_id'], source_schema='swapp', referent_schema='swapp')
    op.create_foreign_key('users_created_by_fkey', 'users', 'users', ['created_by'], ['user_id'], source_schema='swapp', referent_schema='swapp')
    op.drop_index(op.f('ix_swapp_users_email'), table_name='users', schema='swapp')
    op.create_unique_constraint('users_email_key', 'users', ['email'], schema='swapp', postgresql_nulls_not_distinct=False)
    op.create_index('idx_users_username', 'users', ['username'], unique=False, schema='swapp')
    op.create_index('idx_users_user_uuid', 'users', ['user_uuid'], unique=False, schema='swapp')
    op.create_index('idx_users_settings', 'users', ['settings'], unique=False, schema='swapp', postgresql_using='gin')
    op.create_index('idx_users_role', 'users', ['role'], unique=False, schema='swapp')
    op.create_index('idx_users_metadata', 'users', ['metadata'], unique=False, schema='swapp', postgresql_using='gin')
    op.create_index('idx_users_email', 'users', ['email'], unique=False, schema='swapp')
    op.create_index('idx_users_deleted_at', 'users', ['deleted_at'], unique=False, schema='swapp', postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_users_created_at', 'users', ['created_at'], unique=False, schema='swapp')
    op.alter_column('users', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Soft delete: NULL = activo, fecha = eliminado',
               existing_nullable=True,
               schema='swapp')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               comment='Rol del usuario: user, admin, moderator, etc.',
               existing_nullable=False,
               existing_server_default=sa.text("'user'::character varying"),
               schema='swapp')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='Hash de la contraseña (bcrypt/argon2)',
               existing_nullable=False,
               schema='swapp')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Email único del usuario',
               existing_nullable=False,
               schema='swapp')
    op.alter_column('users', 'user_uuid',
               existing_type=sa.UUID(),
               comment='Identificador UUID público para APIs',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'),
               schema='swapp')
    op.alter_column('users', 'user_id',
               existing_type=sa.BIGINT(),
               comment='Identificador numérico autoincremental',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('swapp.users_user_id_seq'::regclass)"),
               schema='swapp')
    op.create_table_comment(
        'user_image_analyses',
        'Registro de imágenes subidas por usuarios y su análisis por IA',
        existing_comment=None,
        schema='swapp'
    )
    op.create_index('idx_user_image_user', 'user_image_analyses', ['user_id'], unique=False, schema='swapp')
    op.create_index('idx_user_image_upload', 'user_image_analyses', ['upload_timestamp'], unique=False, schema='swapp')
    op.create_index('idx_user_image_status', 'user_image_analyses', ['recognition_status'], unique=False, schema='swapp')
    op.create_index('idx_user_image_recognized_product', 'user_image_analyses', ['recognized_product_id'], unique=False, schema='swapp')
    op.create_index('idx_user_image_product', 'user_image_analyses', ['product_id'], unique=False, schema='swapp')
    op.create_index('idx_user_image_modelarts', 'user_image_analyses', ['modelarts_response'], unique=False, schema='swapp', postgresql_using='gin')
    op.create_index('idx_user_image_labels', 'user_image_analyses', ['detected_labels'], unique=False, schema='swapp', postgresql_using='gin')
    op.create_index('idx_user_image_detection', 'user_image_analyses', ['detection_details'], unique=False, schema='swapp', postgresql_using='gin')
    op.create_index('idx_user_image_confidence', 'user_image_analyses', ['confidence_score'], unique=False, schema='swapp')
    op.alter_column('user_image_analyses', 'user_feedback',
               existing_type=sa.VARCHAR(length=20),
               comment='Feedback del usuario: correct, incorrect, not_sure',
               existing_nullable=True,
               schema='swapp')
    op.alter_column('user_image_analyses', 'detection_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Detalles de objetos detectados con bounding boxes',
               existing_nullable=True,
               schema='swapp')
    op.alter_column('user_image_analyses', 'modelarts_response',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Respuesta completa de ModelArts para debugging y reentrenamiento',
               existing_nullable=True,
               schema='swapp')
    op.alter_column('user_image_analyses', 'confidence_score',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               comment='Precisión del reconocimiento (0-1)',
               existing_nullable=True,
               schema='swapp')
    op.alter_column('user_image_analyses', 'recognition_status',
               existing_type=sa.VARCHAR(length=50),
               comment='Estado del reconocimiento: pending, processing, completed, failed, no_match',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"),
               schema='swapp')
    op.alter_column('tax_classes', 'tax_class_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('swapp.tax_classes_tax_class_id_seq'::regclass)"),
               schema='swapp')
    op.drop_index(op.f('ix_swapp_staff_users_staff_id'), table_name='staff_users', schema='swapp')
    op.drop_index(op.f('ix_swapp_staff_users_email'), table_name='staff_users', schema='swapp')
    op.create_unique_constraint('staff_users_email_key', 'staff_users', ['email'], schema='swapp', postgresql_nulls_not_distinct=False)
    op.create_index('idx_staff_users_role', 'staff_users', ['role'], unique=False, schema='swapp')
    op.create_index('idx_staff_users_email', 'staff_users', ['email'], unique=False, schema='swapp')
    op.create_index('idx_staff_users_deleted', 'staff_users', ['deleted_at'], unique=False, schema='swapp', postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_staff_users_active', 'staff_users', ['is_active'], unique=False, schema='swapp')
    op.alter_column('staff_users', 'last_login_user_agent',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               schema='swapp')
    op.create_table_comment(
        'products',
        'Catálogo de productos de la aplicación',
        existing_comment=None,
        schema='swapp'
    )
    op.drop_index(op.f('ix_swapp_products_sku'), table_name='products', schema='swapp')
    op.create_unique_constraint('products_sku_key', 'products', ['sku'], schema='swapp', postgresql_nulls_not_distinct=False)
    op.create_index('idx_products_type', 'products', ['product_type'], unique=False, schema='swapp')
    op.create_index('idx_products_slug', 'products', ['slug'], unique=False, schema='swapp')
    op.create_index('idx_products_sku', 'products', ['sku'], unique=False, schema='swapp')
    op.create_index('idx_products_published', 'products', ['is_published', 'published_at'], unique=False, schema='swapp')
    op.create_index('idx_products_featured', 'products', ['is_featured', 'is_published'], unique=False, schema='swapp')
    op.create_index('idx_products_deleted', 'products', ['deleted_at'], unique=False, schema='swapp', postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_products_created_at', 'products', ['created_at'], unique=False, schema='swapp')
    op.create_index('idx_products_category', 'products', ['category_id'], unique=False, schema='swapp')
    op.alter_column('products', 'tax_class_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               schema='swapp')
    op.alter_column('products', 'is_returnable',
               existing_type=sa.BOOLEAN(),
               comment='Indica si el producto puede ser devuelto por el cliente',
               existing_nullable=False,
               existing_server_default=sa.text('false'),
               schema='swapp')
    op.alter_column('products', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Indica si el producto está activo en el sistema (permite ocultar sin eliminar)',
               existing_nullable=False,
               existing_server_default=sa.text('true'),
               schema='swapp')
    op.alter_column('products', 'cost_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               schema='swapp')
    op.alter_column('products', 'base_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Precio regular sin descuento',
               existing_nullable=False,
               schema='swapp')
    op.alter_column('products', 'slug',
               existing_type=sa.VARCHAR(length=255),
               comment='URL amigable: nombre-del-producto',
               existing_nullable=False,
               schema='swapp')
    op.alter_column('products', 'sku',
               existing_type=sa.VARCHAR(length=50),
               comment='Código único del producto para inventario',
               existing_nullable=True,
               schema='swapp')
    op.drop_constraint(None, 'product_relationships', schema='swapp', type_='foreignkey')
    op.drop_constraint(None, 'product_relationships', schema='swapp', type_='foreignkey')
    op.create_foreign_key('product_relationships_created_by_fkey', 'product_relationships', 'users', ['created_by'], ['user_id'], source_schema='swapp', referent_schema='swapp')
    op.create_foreign_key('product_relationships_updated_by_fkey', 'product_relationships', 'users', ['updated_by'], ['user_id'], source_schema='swapp', referent_schema='swapp')
    op.create_unique_constraint('unique_relationship', 'product_relationships', ['source_product_id', 'target_product_id', 'relationship_type'], schema='swapp', postgresql_nulls_not_distinct=False)
    op.create_index('idx_product_rel_type', 'product_relationships', ['relationship_type'], unique=False, schema='swapp')
    op.create_index('idx_product_rel_target_type', 'product_relationships', ['target_product_id', 'relationship_type'], unique=False, schema='swapp')
    op.create_index('idx_product_rel_target', 'product_relationships', ['target_product_id'], unique=False, schema='swapp')
    op.create_index('idx_product_rel_source_type', 'product_relationships', ['source_product_id', 'relationship_type'], unique=False, schema='swapp')
    op.create_index('idx_product_rel_source', 'product_relationships', ['source_product_id'], unique=False, schema='swapp')
    op.create_index('idx_product_rel_priority', 'product_relationships', [sa.text('priority DESC')], unique=False, schema='swapp')
    op.create_index('idx_product_rel_confidence', 'product_relationships', [sa.text('confidence_score DESC')], unique=False, schema='swapp')
    op.create_table_comment(
        'product_price_history',
        'Registro inmutable de los cambios de precio de los productos',
        existing_comment=None,
        schema='swapp'
    )
    op.alter_column('product_price_history', 'record_type',
               existing_type=sa.VARCHAR(length=20),
               comment='Indica si el cambio fue en el precio de venta (base_price) o costo de reposición (cost_price)',
               existing_nullable=False,
               existing_server_default=sa.text("'base_price'::character varying"),
               schema='swapp')
    op.create_index('idx_product_media_type', 'product_media', ['media_type'], unique=False, schema='swapp')
    op.create_index('idx_product_media_product', 'product_media', ['product_id'], unique=False, schema='swapp')
    op.create_index('idx_product_media_order', 'product_media', ['product_id', 'display_order'], unique=False, schema='swapp')
    op.create_table_comment(
        'product_discounts',
        'Motor de ofertas temporales por producto',
        existing_comment=None,
        schema='swapp'
    )
    op.create_index('idx_discounts_product', 'product_discounts', ['product_id'], unique=False, schema='swapp')
    op.create_index('idx_discounts_dates', 'product_discounts', ['start_date', 'end_date'], unique=False, schema='swapp')
    op.create_table_comment(
        'product_categories',
        'Categorías jerárquicas de productos',
        existing_comment=None,
        schema='swapp'
    )
    op.create_index('idx_categories_slug', 'product_categories', ['slug'], unique=False, schema='swapp')
    op.create_index('idx_categories_path_ids', 'product_categories', ['path_ids'], unique=False, schema='swapp', postgresql_using='gin')
    op.create_index('idx_categories_parent', 'product_categories', ['parent_id'], unique=False, schema='swapp')
    op.create_index('idx_categories_level', 'product_categories', ['level'], unique=False, schema='swapp')
    op.alter_column('product_categories', 'level',
               existing_type=sa.INTEGER(),
               comment='Nivel: 1=raíz, 2=hijo, 3=nieto, etc.',
               existing_nullable=True,
               schema='swapp')
    op.alter_column('product_categories', 'parent_id',
               existing_type=sa.BIGINT(),
               comment='Categoría padre (NULL si es nivel 1)',
               existing_nullable=True,
               schema='swapp')
    op.drop_index(op.f('ix_swapp_inventory_movements_movement_id'), table_name='inventory_movements', schema='swapp')
    op.create_index('idx_inventory_movements_type', 'inventory_movements', ['movement_type'], unique=False, schema='swapp')
    op.create_index('idx_inventory_movements_reference', 'inventory_movements', ['reference_id', 'reference_type'], unique=False, schema='swapp')
    op.create_index('idx_inventory_movements_product', 'inventory_movements', ['product_id'], unique=False, schema='swapp')
    op.create_index('idx_inventory_movements_created', 'inventory_movements', ['created_at'], unique=False, schema='swapp')
    op.alter_column('inventory_movements', 'unit_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Costo por unidad pagado en este lote (obligatorio para purchases)',
               existing_nullable=True,
               schema='swapp')
    op.alter_column('inventory_movements', 'movement_uuid',
               existing_type=sa.UUID(),
               nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'),
               schema='swapp')
    # ### end Alembic commands ###
