"""Add refill_price, product model, and returnable tables

Revision ID: 4b0523757acf
Revises: 56ffd802bb24
Create Date: 2026-09-09 22:24:34.159387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b0523757acf'
down_revision: Union[str, None] = '56ffd802bb24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('reference_refill_price', sa.Numeric(precision=10, scale=2), nullable=True), schema='swapp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'reference_refill_price', schema='swapp')
    # ### end Alembic commands ###
