"""Agregamos refill_price a ProductVariant

Revision ID: 56ffd802bb24
Revises: 7e4ef5236677
Create Date: 2026-09-09 19:30:09.696381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56ffd802bb24'
down_revision: Union[str, None] = '7e4ef5236677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('refill_price', sa.Numeric(precision=10, scale=2), nullable=True), schema='swapp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_variants', 'refill_price', schema='swapp')
    # ### end Alembic commands ###
