"""create_product_variants_table_and_extract_columns

Revision ID: 65407143f7a8
Revises: 4653a8cbeab6
Create Date: 2026-08-18 19:43:40.857877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65407143f7a8'
down_revision: Union[str, None] = '4653a8cbeab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS trg_log_price_change ON swapp.products CASCADE")

    op.drop_index('ix_swapp_products_sku', table_name='products', schema='swapp')
    op.drop_column('products', 'sku', schema='swapp')
    op.drop_column('products', 'stock_quantity', schema='swapp')
    op.drop_column('products', 'variant_attributes', schema='swapp')
    op.drop_column('products', 'cost_price', schema='swapp')
    op.drop_column('products', 'base_price', schema='swapp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('base_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False), schema='swapp')
    op.add_column('products', sa.Column('cost_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False), schema='swapp')
    op.add_column('products', sa.Column('variant_attributes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True), schema='swapp')
    op.add_column('products', sa.Column('stock_quantity', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True), schema='swapp')
    op.add_column('products', sa.Column('sku', sa.VARCHAR(length=50), autoincrement=False, nullable=True), schema='swapp')
    op.create_index('ix_swapp_products_sku', 'products', ['sku'], unique=True, schema='swapp')
    # ### end Alembic commands ###
