"""Agregado modulo de ordenes e items

Revision ID: 6b0198adce6a
Revises: c7178d385fe7
Create Date: 2026-08-26 13:52:14.407271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b0198adce6a'
down_revision: Union[str, None] = 'c7178d385fe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
