"""add_is_internal_to_products

Revision ID: 6f2547306c04
Revises: 4b0523757acf
Create Date: 2026-09-21 14:08:57.007046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f2547306c04'
down_revision: Union[str, None] = '4b0523757acf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_internal', sa.Boolean(), nullable=False, server_default='false'), schema='swapp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_internal', schema='swapp')
    # ### end Alembic commands ###
