"""Agrega Ledger de envases a clientes

Revision ID: 7e4ef5236677
Revises: 8aa230d11c8b
Create Date: 2026-09-09 18:42:46.630974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e4ef5236677'
down_revision: Union[str, None] = '8aa230d11c8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('returnable_physical_stock',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('stock_full', sa.Integer(), nullable=False),
    sa.Column('reserved_stock', sa.Integer(), nullable=False),
    sa.Column('stock_empty', sa.Integer(), nullable=False),
    sa.Column('stock_quarantine', sa.Integer(), nullable=False),
    sa.Column('last_audited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['swapp.products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id'),
    schema='swapp'
    )
    op.create_table('client_container_ledger',
    sa.Column('ledger_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ledger_uuid', sa.UUID(), nullable=True),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('quantity_change', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['swapp.clients.client_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['swapp.orders.order_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['swapp.products.product_id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['swapp.staff_users.staff_id'], ),
    sa.PrimaryKeyConstraint('ledger_id'),
    sa.UniqueConstraint('ledger_uuid'),
    schema='swapp'
    )
    op.add_column('products', sa.Column('model', sa.String(length=100), nullable=True), schema='swapp')
    op.create_index(op.f('ix_swapp_products_model'), 'products', ['model'], unique=False, schema='swapp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_swapp_products_model'), table_name='products', schema='swapp')
    op.drop_column('products', 'model', schema='swapp')
    op.drop_table('client_container_ledger', schema='swapp')
    op.drop_table('returnable_physical_stock', schema='swapp')
    # ### end Alembic commands ###
