"""auto_add_image_url_to_variants

Revision ID: 85c7e4ae105d
Revises: ccb943c52da4
Create Date: 2026-08-21 12:36:55.519884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85c7e4ae105d'
down_revision: Union[str, None] = 'ccb943c52da4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory_movements', 'variant_id',
               existing_type=sa.BIGINT(),
               nullable=False,
               schema='swapp')
    op.add_column('product_variants', sa.Column('image_url', sa.String(length=500), nullable=True), schema='swapp')
    op.alter_column('products', 'reference_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.0'),
               schema='swapp')
    op.alter_column('products', 'reference_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.0'),
               schema='swapp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'reference_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.0'),
               schema='swapp')
    op.alter_column('products', 'reference_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.0'),
               schema='swapp')
    op.drop_column('product_variants', 'image_url', schema='swapp')
    op.alter_column('inventory_movements', 'variant_id',
               existing_type=sa.BIGINT(),
               nullable=True,
               schema='swapp')
    # ### end Alembic commands ###
