"""Creacion tabla clients y actualizacion de orders

Revision ID: 8aa230d11c8b
Revises: 416336249dc3
Create Date: 2026-09-09 11:48:31.377982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8aa230d11c8b'
down_revision: Union[str, None] = '416336249dc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('client_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('client_uuid', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('default_delivery_address', sa.Text(), nullable=False),
    sa.Column('default_delivery_zone', sa.String(length=100), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['swapp.staff_users.staff_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['swapp.staff_users.staff_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['swapp.users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('client_uuid'),
    sa.UniqueConstraint('whatsapp_number'),
    schema='swapp'
    )
    op.add_column('orders', sa.Column('client_id', sa.BigInteger(), nullable=False), schema='swapp')
    op.create_foreign_key(None, 'orders', 'clients', ['client_id'], ['client_id'], source_schema='swapp', referent_schema='swapp', ondelete='RESTRICT')
    op.drop_column('orders', 'customer_phone', schema='swapp')
    op.drop_column('orders', 'customer_name', schema='swapp')
    op.drop_column('orders', 'customer_email', schema='swapp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True), schema='swapp')
    op.add_column('orders', sa.Column('customer_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False), schema='swapp')
    op.add_column('orders', sa.Column('customer_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=False), schema='swapp')
    op.drop_constraint(None, 'orders', schema='swapp', type_='foreignkey')
    op.drop_column('orders', 'client_id', schema='swapp')
    op.drop_table('clients', schema='swapp')
    # ### end Alembic commands ###
