"""Eliminar reference cost y price

Revision ID: a66848254d7d
Revises: b57093acd705
Create Date: 2026-09-23 13:07:15.670347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a66848254d7d'
down_revision: Union[str, None] = 'b57093acd705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'reference_cost', schema='swapp')
    op.drop_column('products', 'reference_refill_price', schema='swapp')
    op.drop_column('products', 'reference_price', schema='swapp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('reference_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True), schema='swapp')
    op.add_column('products', sa.Column('reference_refill_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True), schema='swapp')
    op.add_column('products', sa.Column('reference_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True), schema='swapp')
    # ### end Alembic commands ###
