"""add is_global

Revision ID: b57093acd705
Revises: 6f2547306c04
Create Date: 2026-09-22 18:21:54.639519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b57093acd705'
down_revision: Union[str, None] = '6f2547306c04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_attributes', sa.Column('is_global', sa.Boolean(), nullable=True), schema='swapp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_attributes', 'is_global', schema='swapp')
    # ### end Alembic commands ###
