"""remove_legacy_logistics_columns

Revision ID: b584e43d3b38
Revises: a66848254d7d
Create Date: 2026-09-25 13:37:57.381960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b584e43d3b38'
down_revision: Union[str, None] = 'a66848254d7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_variants', 'refill_price', schema='swapp')
    op.drop_column('products', 'is_returnable', schema='swapp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_returnable', sa.BOOLEAN(), autoincrement=False, nullable=False), schema='swapp')
    op.add_column('product_variants', sa.Column('refill_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True), schema='swapp')
    # ### end Alembic commands ###
