"""Agregamos linked_internal_product_id a swapp.products

Revision ID: c3074a074f8a
Revises: fe6afdbc8e5f
Create Date: 2026-09-28 14:20:35.345183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3074a074f8a'
down_revision: Union[str, None] = 'fe6afdbc8e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('linked_internal_product_id', sa.BigInteger(), nullable=True), schema='swapp')
    op.create_foreign_key(None, 'products', 'products', ['linked_internal_product_id'], ['product_id'], source_schema='swapp', referent_schema='swapp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', schema='swapp', type_='foreignkey')
    op.drop_column('products', 'linked_internal_product_id', schema='swapp')
    # ### end Alembic commands ###
