"""migracion_inicial

Revision ID: f8df712d45cd
Revises: 
Create Date: 2026-07-28 20:00:11.963619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8df712d45cd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('brand_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('brand_uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('brand_id'),
    sa.UniqueConstraint('brand_uuid'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug'),
    schema='swapp'
    )
    op.create_table('product_categories',
    sa.Column('category_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('category_uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['swapp.product_categories.category_id'], ),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_uuid'),
    sa.UniqueConstraint('slug'),
    schema='swapp'
    )
    op.create_table('staff_users',
    sa.Column('staff_id', sa.BigInteger(), nullable=False),
    sa.Column('staff_uuid', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('login_attempts', sa.Integer(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', postgresql.INET(), nullable=True),
    sa.Column('last_login_user_agent', sa.String(), nullable=True),
    sa.Column('two_factor_secret', sa.String(length=255), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['swapp.staff_users.staff_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['swapp.staff_users.staff_id'], ),
    sa.PrimaryKeyConstraint('staff_id'),
    sa.UniqueConstraint('staff_uuid'),
    schema='swapp'
    )
    op.create_index(op.f('ix_swapp_staff_users_email'), 'staff_users', ['email'], unique=True, schema='swapp')
    op.create_index(op.f('ix_swapp_staff_users_staff_id'), 'staff_users', ['staff_id'], unique=False, schema='swapp')
    op.create_table('tax_classes',
    sa.Column('tax_class_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('tax_class_id'),
    schema='swapp'
    )
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_uuid'),
    sa.UniqueConstraint('username'),
    schema='swapp'
    )
    op.create_index(op.f('ix_swapp_users_email'), 'users', ['email'], unique=True, schema='swapp')
    op.create_table('products',
    sa.Column('product_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_uuid', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('brand_id', sa.BigInteger(), nullable=True),
    sa.Column('tax_class_id', sa.BigInteger(), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('main_image_url', sa.Text(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('sold_count', sa.Integer(), nullable=True),
    sa.Column('is_returnable', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['swapp.brands.brand_id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['swapp.product_categories.category_id'], ),
    sa.ForeignKeyConstraint(['tax_class_id'], ['swapp.tax_classes.tax_class_id'], ),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('product_uuid'),
    sa.UniqueConstraint('slug'),
    schema='swapp'
    )
    op.create_index(op.f('ix_swapp_products_sku'), 'products', ['sku'], unique=True, schema='swapp')
    op.create_table('inventory_movements',
    sa.Column('movement_id', sa.BigInteger(), nullable=False),
    sa.Column('movement_uuid', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('movement_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stock_before', sa.Integer(), nullable=True),
    sa.Column('stock_after', sa.Integer(), nullable=True),
    sa.Column('reference_id', sa.BigInteger(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['swapp.users.user_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['swapp.products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movement_id'),
    sa.UniqueConstraint('movement_uuid'),
    schema='swapp'
    )
    op.create_index(op.f('ix_swapp_inventory_movements_movement_id'), 'inventory_movements', ['movement_id'], unique=False, schema='swapp')
    op.create_table('product_discounts',
    sa.Column('discount_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('discount_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['swapp.products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('discount_id'),
    schema='swapp'
    )
    op.create_table('product_price_history',
    sa.Column('history_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('old_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('new_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('record_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['swapp.products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('history_id'),
    schema='swapp'
    )
    op.create_table('product_relationships',
    sa.Column('relationship_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('relationship_uuid', sa.UUID(), nullable=False),
    sa.Column('source_product_id', sa.BigInteger(), nullable=False),
    sa.Column('target_product_id', sa.BigInteger(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('is_bidirectional', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_product_id'], ['swapp.products.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_product_id'], ['swapp.products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('relationship_id'),
    sa.UniqueConstraint('relationship_uuid'),
    schema='swapp'
    )
    op.create_table('user_image_analyses',
    sa.Column('analysis_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('analysis_uuid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('recognized_product_id', sa.BigInteger(), nullable=True),
    sa.Column('recognition_status', sa.String(length=50), nullable=True),
    sa.Column('user_corrected_product_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['swapp.products.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recognized_product_id'], ['swapp.products.product_id'], ),
    sa.ForeignKeyConstraint(['user_corrected_product_id'], ['swapp.products.product_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['swapp.users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('analysis_id'),
    sa.UniqueConstraint('analysis_uuid'),
    schema='swapp'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_image_analyses', schema='swapp')
    op.drop_table('product_relationships', schema='swapp')
    op.drop_table('product_price_history', schema='swapp')
    op.drop_table('product_discounts', schema='swapp')
    op.drop_index(op.f('ix_swapp_inventory_movements_movement_id'), table_name='inventory_movements', schema='swapp')
    op.drop_table('inventory_movements', schema='swapp')
    op.drop_index(op.f('ix_swapp_products_sku'), table_name='products', schema='swapp')
    op.drop_table('products', schema='swapp')
    op.drop_index(op.f('ix_swapp_users_email'), table_name='users', schema='swapp')
    op.drop_table('users', schema='swapp')
    op.drop_table('tax_classes', schema='swapp')
    op.drop_index(op.f('ix_swapp_staff_users_staff_id'), table_name='staff_users', schema='swapp')
    op.drop_index(op.f('ix_swapp_staff_users_email'), table_name='staff_users', schema='swapp')
    op.drop_table('staff_users', schema='swapp')
    op.drop_table('product_categories', schema='swapp')
    op.drop_table('brands', schema='swapp')
    # ### end Alembic commands ###
