"""adding internal_product_id to orders

Revision ID: fe6afdbc8e5f
Revises: b584e43d3b38
Create Date: 2026-09-25 15:46:47.081802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe6afdbc8e5f'
down_revision: Union[str, None] = 'b584e43d3b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('internal_product_id', sa.BigInteger(), nullable=True), schema='swapp')
    op.add_column('order_items', sa.Column('internal_variant_id', sa.BigInteger(), nullable=True), schema='swapp')
    op.create_foreign_key(None, 'order_items', 'products', ['internal_product_id'], ['product_id'], source_schema='swapp', referent_schema='swapp')
    op.create_foreign_key(None, 'order_items', 'product_variants', ['internal_variant_id'], ['variant_id'], source_schema='swapp', referent_schema='swapp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', schema='swapp', type_='foreignkey')
    op.drop_constraint(None, 'order_items', schema='swapp', type_='foreignkey')
    op.drop_column('order_items', 'internal_variant_id', schema='swapp')
    op.drop_column('order_items', 'internal_product_id', schema='swapp')
    # ### end Alembic commands ###
