import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import Header from "@/components/swapp/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Swapp Demo",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="es">
			<body
				className={`${inter.className} bg-gray-200 min-h-screen flex justify-center`}>
				{/* Proveedor de Autenticación */}
				<AuthProvider>
					{/* Simulador de Móvil */}
					<div className="w-full max-w-md bg-white min-h-screen shadow-2xl relative flex flex-col overflow-hidden">
						<Header />

						{/* --- CONTENIDO DINÁMICO --- */}
						<main className="flex-1 overflow-y-auto bg-[linear-gradient(to_bottom,#172638_0%,#132D46_10%,#0A786A_20%,#01C38E_35%,#80E1C7_45%,#FFFFFF_60%,#f0f1f4_70%)] pb-24">
							{children}
						</main>

						{/* --- BOTTOM NAVIGATION (Esto se queda igual) --- */}
						<nav className="absolute bottom-0 w-full bg-gray-200 h-20">
							<div className="absolute bottom-0 w-full h-28 bg-white rounded-t-[30px] shadow-[0_-5px_20px_rgba(0,0,0,0.1)] flex justify-between items-center px-10 z-10">
								<button className="text-swapp-dark hover:text-swapp-mint transition">
									<svg
										className="w-9 h-9"
										fill="none"
										stroke="currentColor"
										viewBox="0 0 24 24">
										<path
											strokeLinecap="round"
											strokeLinejoin="round"
											strokeWidth={2}
											d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"
										/>
									</svg>
								</button>
								<button className="text-swapp-dark hover:text-swapp-mint transition">
									<svg
										className="w-9 h-9"
										fill="none"
										stroke="currentColor"
										viewBox="0 0 24 24">
										<path
											strokeLinecap="round"
											strokeLinejoin="round"
											strokeWidth={2}
											d="M4 6h16M4 12h16M4 18h16"
										/>
									</svg>
								</button>
							</div>
							<div className="absolute bottom-16 left-1/2 transform -translate-x-1/2 z-20">
								<button className="w-20 h-20 bg-[linear-gradient(to_bottom,#172638_0%,#132D46_20%,#0A786A_100%)] rounded-full shadow-lg border-4 border-gray-200 flex items-center justify-center text-white hover:scale-105 transition">
									<svg
										className="w-8 h-8"
										fill="none"
										stroke="currentColor"
										viewBox="0 0 24 24">
										<path
											strokeLinecap="round"
											strokeLinejoin="round"
											strokeWidth={2}
											d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z"
										/>
									</svg>
								</button>
							</div>
						</nav>
					</div>
				</AuthProvider>
			</body>
		</html>
	);
}
